# Generated by Django 5.2.12 on 2026-04-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
